language: "ko-KR"  # 한국어로 리뷰
early_access: false

reviews:
  profile: "chill"  # 리뷰 톤을 부드럽게
  request_changes_workflow: false  # 리뷰 후 PR 승인 기능 비활성화
  high_level_summary: true  # 요약 포함 (요약만 생성)
  poem: true  # 짧은 시 포함 가능
  review_status: true  # 리뷰 상태 표시
  collapse_walkthrough: false  # 리뷰 설명 펼치기
  auto_review:
    enabled: false  # 자동 리뷰 비활성화 (요약만 수행)
    drafts: false  # draft PR은 제외

chat:
  auto_reply: true  # 코멘트에 자동 답변 활성화
